# Site settings
title: ConnectorDB
email: support@connectordb.com
description: > # this means to ignore newlines until "baseurl:"
  An Open-Source database for Quantified Self & IoT
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://connectordb.github.com" # the base hostname & protocol for your site
twitter_username: connectordb
github_username:  connectordb
host: 0.0.0.0
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
